---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fabric
  namespace: ledger

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: fabric
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabric
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - fabric

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric
roleRef:
  kind: ClusterRole
  name: fabric
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fabric
  namespace: ledger
