---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric
  labels:
    app: fabric
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hyperledger/fabric"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hyperledger
  name: fabric
  labels:
    app: fabric
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
