---
apiVersion: v1
kind: Service
metadata:
  name: caorg1
  namespace: hyperledger
spec:
  type: ClusterIP
  selector:
    app: caorg1
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caorg1
  namespace: hyperledger
  labels:
    app: caorg1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caorg1
  template:
    metadata:
      labels:
        app: caorg1
    spec:
      containers:
      - name: caorg1
        image: hyperledger/fabric-ca:latest
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
        ports:
        - containerPort: 7054
        env:
        - name: TZ
          value: "Europe/London"
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "CA1"
        - name: FABRIC_CA_SERVER_CA_CERTFILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
        - name: FABRIC_CA_SERVER_CA_KEYFILE
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/ca/key.pem
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /certs/ca0a-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /certs/ca0a-key.pem
        - name: GODEBUG
          value: "netdns=go"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric
---
apiVersion: v1
kind: Service
metadata:
  name: org1peer1
  namespace: hyperledger
spec:
  type: ClusterIP
  selector:
    app: org1peer1
  ports:
  - protocol: TCP
    targetPort: 30110
    port: 30110
    name: grpc
  - protocol: TCP
    targetPort: 30111
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1peer1
  namespace: hyperledger
  labels:
    app: org1peer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org1peer1
  template:
    metadata:
      labels:
        app: org1peer1
    spec:
      containers:
      - name: org1peer1
        image: hyperledger/fabric-peer:1.4.3
        command: ["sh", "-c", "peer node start"]
        env:
        - name: TZ
          value: "Europe/London"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ID
          value: org1peer1
        - name: CORE_PEER_ADDRESS
          value: 127.0.0.1:30110
        #- name: CORE_PEER_CHAINCODELISTENADDRESS
        #  value: "localhost:30110"
        #CORE_PEER_GOSSIP_EXTERNALENDPOINT for Hyperledger Explorer
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: 127.0.0.1:30110
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30110
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30111
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: 127.0.0.1:30110
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: 127.0.0.1:30110
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: "http://localhost:2375"
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_LOGGING_PEER
          value: info
        - name: CORE_LOGGING_CAUTHDSL
          value: info
        - name: CORE_LOGGING_GOSSIP
          value: info
        - name: CORE_LOGGING_LEDGER
          value: info
        - name: CORE_LOGGING_MSP
          value: info
        - name: CORE_LOGGING_POLICIES
          value: info
        - name: CORE_LOGGING_GRPC
          value: info
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: "admin"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: "admin"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        ports:
        - containerPort: 30110
        - containerPort: 30111
      - name: couchdb
        image: hyperledger/fabric-couchdb
        env:
        - name: TZ
          value: "Europe/London"
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "admin"
      - name: dind
        image: docker:20.10-dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric
      - name: dind-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: org1peer2
  namespace: hyperledger
spec:
  type: ClusterIP
  selector:
    app: org1peer2
  ports:
  - protocol: TCP
    targetPort: 30110
    port: 30110
    name: grpc
  - protocol: TCP
    targetPort: 30111
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1peer2
  namespace: hyperledger
  labels:
    app: org1peer2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org1peer2
  template:
    metadata:
      labels:
        app: org1peer2
    spec:
      containers:
      - name: org1peer2
        image: hyperledger/fabric-peer:1.4.3
        command: ["sh", "-c", "peer node start"]
        env:
        - name: TZ
          value: "Europe/London"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ID
          value: org1peer2
        - name: CORE_PEER_ADDRESS
          value: 127.0.0.1:30110
        #- name: CORE_PEER_CHAINCODELISTENADDRESS
        #  value: "localhost:30110"
        #CORE_PEER_GOSSIP_EXTERNALENDPOINT for Hyperledger Explorer
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: 127.0.0.1:30110
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30110
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30111
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: 127.0.0.1:30110
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: 127.0.0.1:30110
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: "http://localhost:2375"
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_LOGGING_PEER
          value: info
        - name: CORE_LOGGING_CAUTHDSL
          value: info
        - name: CORE_LOGGING_GOSSIP
          value: info
        - name: CORE_LOGGING_LEDGER
          value: info
        - name: CORE_LOGGING_MSP
          value: info
        - name: CORE_LOGGING_POLICIES
          value: info
        - name: CORE_LOGGING_GRPC
          value: info
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: "admin"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: "admin"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        ports:
        - containerPort: 30110
        - containerPort: 30111
      - name: couchdb
        image: hyperledger/fabric-couchdb
        env:
        - name: TZ
          value: "Europe/London"
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "admin"
      - name: dind
        image: docker:20.10-dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric
      - name: dind-storage
        emptyDir: {}
