---
apiVersion: v1
kind: Service
metadata:
  name: org3peer1
  namespace: ledger
spec:
  type: ClusterIP
  selector:
    app: org3peer1
  ports:
  - protocol: TCP
    targetPort: 30310
    port: 30310
    name: grpc
  - protocol: TCP
    targetPort: 30311
    port: 30311
    name: events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org3peer1
  namespace: ledger
  labels:
    app: org3peer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org3peer1
  template:
    metadata:
      labels:
        app: org3peer1
    spec:
      containers:
      - name: org3peer1
        image: hyperledger/fabric-peer:1.4.3
        command: ["sh", "-c", "sleep 1 && while [ ! -f /fabric/status_configtxgen_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start"]
        env:
        - name: TZ
          value: "Europe/London"
        - name: CORE_CHAINCODE_BUILDER
          value: "hyperledger/fabric-ccenv:1.4"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ID
          value: org3peer1
        - name: CORE_PEER_ADDRESS
          value: 127.0.0.1:30310
        #- name: CORE_PEER_CHAINCODELISTENADDRESS
        #  value: "localhost:30310"
        #CORE_PEER_GOSSIP_EXTERNALENDPOINT for Hyperledger Explorer
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: 127.0.0.1:30310
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30310
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:30311
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: 127.0.0.1:30310
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: 127.0.0.1:30310
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: "tcp://docker:2375"
        - name: CORE_PEER_LOCALMSPID
          value: Org3MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp/
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_LOGGING_PEER
          value: info
        - name: CORE_LOGGING_CAUTHDSL
          value: info
        - name: CORE_LOGGING_GOSSIP
          value: info
        - name: CORE_LOGGING_LEDGER
          value: info
        - name: CORE_LOGGING_MSP
          value: info
        - name: CORE_LOGGING_POLICIES
          value: info
        - name: CORE_LOGGING_GRPC
          value: info
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: "admin"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: "admin"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        ports:
        - containerPort: 30310
        - containerPort: 30311
      - name: couchdb
        image: hyperledger/fabric-couchdb
        env:
        - name: TZ
          value: "Europe/London"
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "admin"
      serviceAccountName: fabric
      volumes:
      - name: fabricfiles
        nfs:
          server: nfs-server.ledger.svc.cluster.local
          path: "/"
